#cloud-config
timezone: Asia/Tokyo
locale: en_US.UTF-8
packages:
  - nginx
package_update: true
package_upgrade: true

runcmd:
  - curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
  - bash add-google-cloud-ops-agent-repo.sh --also-install
  - apt-get update
  - apt-get upgrade -y
  - systemctl enable nginx
  - systemctl start nginx
  - systemctl enable google-cloud-ops-agent
  - systemctl start google-cloud-ops-agent

# https://cloud.google.com/blog/products/operations/use-ansible-to-deploy-the-google-cloud-ops-agent
write_files:
  - path: /etc/google-cloud-ops-agent/config.yaml
    permissions: 0644
    owner: root
    content: |
      logging:
        receivers:
          nginx_default_access:
            type: nginx_access
          nginx_default_error:
            type: nginx_error
        service:
          pipelines:
            nginx:
              receivers:
                - nginx_default_access
                - nginx_default_error
      metrics:
        receivers:
          nginx_metrics:
            type: nginx
            stub_status_url: http://127.0.0.1:80/status
            collection_interval: 60s
        service:
          pipelines:
            nginx_pipeline:
              receivers:
                - nginx_metrics

  - path: /etc/nginx/conf.d/status.conf
    permissions: 0644
    owner: root
    content: |
      server {
          listen 80;
          server_name 127.0.0.1;
          location /status {
              stub_status on;
              access_log off;
              allow 127.0.0.1;
              deny all;
          }
          location / {
            root /dev/null;
          }
      }

# reboot after all configurations
power_state:
  delay: now
  mode: reboot
